version = "1"

[general]
  auto_update = true
  embedding = false
  interval = "1m"
  polling = true
  serving = false
  tailing = false
  track_state = true

[polling]
  engine = "mssql"
  dbname = "SophosSecurity"
  output_file = "/var/log/sophos-security-audit.log"
  password = "changeme"
  port = "changeme"
  server = "changeme"
  tls = "disable"
  username = "changeme\\changeme"

  [[polling.queries]]
    name = "get_events"
    order = 1
    primary_index = "EventId"
    query = "SELECT * FROM Reports.vAuditEventsAll WHERE EventId > ? ORDER BY EventId"
    starting_index_value = "-1"

[state]
  state_backend = "boltdb"
  state_db = "/opt/sedara/state/dbpoller-sophos-security-audit.db"
